[versions]
# The java-compilation version is the latest supported (not necessarily LTS) version of Java. It should be identical to Java-version used in `actions/setup-java`
java-compilation = "21"
# The java-target version is the lowest supported LTS version of Java. Jar's produced are bytecode compatible with this version.
java-target = "8"
kotlin = "2.0.10"
kotlinDev = "2.0.10"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
checksum = "org.gradle.crypto.checksum:1.4.0"
shadow = "com.gradleup.shadow:8.3.0"
kotlinx-binary-compatibiltiy-validator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.16.3"

[libraries]
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-plugin-dev = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinDev" }
clikt = "com.github.ajalt.clikt:clikt:4.4.0"
dokka = "org.jetbrains.dokka:dokka-gradle-plugin:1.9.20"
ec4j = "org.ec4j.core:ec4j-core:0.3.0"
logging = "io.github.oshai:kotlin-logging-jvm:7.0.0"
slf4j = "org.slf4j:slf4j-simple:2.0.16"
poko = "dev.drewhamilton.poko:poko-gradle-plugin:0.16.0"
# Use logback-classic as the logger for kotlin-logging / slf4j as it allow changing the log level at runtime.
# TODO: Update "renovate.json" once logback-classic is updated to 1.4 (once java8 support for ktlint is dropped)
logback = "ch.qos.logback:logback-classic:1.3.14"
logcaptor = "io.github.hakky54:logcaptor:2.9.3"
# Required for logback-test.xml conditional configuration so that trace-logging in unit test can be automatically enabled using an
# environment variable
janino = "org.codehaus.janino:janino:3.1.12"
# Testing libraries
junit5 = "org.junit.jupiter:junit-jupiter:5.10.3"
assertj = "org.assertj:assertj-core:3.26.3"
sarif4k = "io.github.detekt.sarif4k:sarif4k:0.6.0"
jimfs = "com.google.jimfs:jimfs:1.3.0"
