name: Finish (announce) release 1.7.0

on: [ workflow_dispatch ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'pinterest/ktlint'

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: 'master'

      - uses: ./.github/actions/setup-gradle-build

      - name: Announce 1.7.0 release
        if: ${{ success() }}
        run: |
          git config user.email "ktlint@github.com"
          git config user.name "Ktlint Release Workflow" |
          ./.announce170 -y
        env:
          VERSION: ${{ env.version }}
