# name must be identical to name of 'pull-request-with-code'
name: Pull request

on:
  push:
    branches: ['master']
    paths:
      - '**/*'
      - '!**/*.kt'
      - '!**/*.kts'
      - '!**/*.properties'
      - '!**/*.toml'
  pull_request:
    paths:
      - '**/*'
      - '!**/*.kt'
      - '!**/*.kts'
      - '!**/*.properties'
      - '!**/*.toml'

# Add a dummy job that return true so that a PR not containing any code can be merged to master
# Note that "jobs.build.strategy" and "jobs.build.runs-on" should be kept in sync with "pull-request-wth-code"
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        # When changing the list of JDK versions, the build configuration has to be changed by a repository admin. See
        # https://github.com/pinterest/ktlint/pull/1787#issuecomment-1409074092
        jdk: [8, 11, 17, 20]
        exclude: # windows with JDK8 are *really* flaky
          - os: windows-latest
            jdk: 8
    runs-on: ${{ matrix.os }}
    steps:
      - run: 'echo "No build required"'
