# name must be identical to name of 'pull-request-with-code'
name: Pull request
permissions:
  contents: read

on:
  push:
    branches: ['master']
    paths:
      - '**/*'
      - '!**/*.kt'
      - '!**/*.kts'
      - '!**/*.properties'
      - '!**/*.toml'
  pull_request:
    paths:
      - '**/*'
      - '!**/*.kt'
      - '!**/*.kts'
      - '!**/*.properties'
      - '!**/*.toml'

# Add a dummy job that return true so that a PR not containing any code can be merged to master
# Note that all "jobs" (build, tests) including "jobs.*.runs-on" should be kept in sync with "pull-request-with-code"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: "[build] OS=${{ matrix.os }} Kotlin=stable"
    steps:
      - run: 'echo "No build required"'

  build-dev:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: "[build] OS=${{ matrix.os }}, Kotlin=dev"
    steps:
      - run: 'echo "No build required"'

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: [ 8, 11, 17, 21 ] # list of Java versions (usually only LTS versions) to run tests against (excluding `java-compilation` version for which tests already have run during `build` job)
    runs-on: ${{ matrix.os }}
    name: "[tests] OS=${{ matrix.os }}, Java=${{ matrix.jdk }}"
    steps:
      - run: 'echo "No build required"'
