name: Publish Release

on :
  push :
    tags :
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'pinterest/ktlint'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19
      - uses: gradle/gradle-build-action@v2
      - name: Build executable and publish to Maven
        run: ./gradlew clean shadowJarExecutable publishMavenPublicationToMavenCentralRepository --no-daemon --no-parallel
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey : ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
          ORG_GRADLE_PROJECT_signingKeyPassword : ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}

      - name : Extract release notes
        id : release_notes
        if: ${{ success() }}
        uses : ffurrer2/extract-release-notes@v1

      - name : Create release
        id: github_release
        if: ${{ success() }}
        uses : softprops/action-gh-release@v1
        with :
          draft: false
          prerelease: false
          body : ${{ steps.release_notes.outputs.release_notes }}
          files: |
            ktlint/build/run/*
        env :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        if: ${{ success() }}
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      
      - name: Bump Homebrew Formula
        if: ${{ success() }}
        uses: mislav/bump-homebrew-formula-action@v2
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
        with:
          formula-name: ktlint
          download-url: https://github.com/pinterest/ktlint/releases/download/${{ env.version }}/ktlint

      - name: Announce Release
        if: ${{ success() }}
        run: |
          git config user.email "<>" |
          git config user.name "Ktlint Release Workflow" |
          ./.announce -y
        env:
          VERSION: ${{ env.version }}

